package pedroPathing.robot_state;

public enum RobotState {
    // ===== GENERAL =====
    INIT,
    HOLD,
    TEST,

    // ===== SAMPLE (BUCKET) MODE STATES =====
    // Intake sequence
    SAMPLE_INTAKE_CLOSE,
    SAMPLE_INTAKE_CLAW_CLOSE,
    SAMPLE_INTAKE_WRIST_MOVE,
    SAMPLE_INTAKE_RELEASE_ELBOWS,
    SAMPLE_INTAKE_SLIDES_CONTRACT,
    SAMPLE_INTAKE_CLAW_OPEN,
    SAMPLE_INTAKE_CLAW_OPEN_WAIT,
    SAMPLE_INTAKE_AVOID_CONFLICT,
    SAMPLE_INTAKE_HOLD_OPTION,
    SAMPLE_INTAKE_CANCEL,
    SAMPLE_INTAKE_POSITION_CHECK,
    COMPLETE_INTAKE,
    SAMPLE_INTAKE_GRAB,
    SAMPLE_INTAKE_CHECK_SAMPLE,
    SAMPLE_INTAKE_TARGET_CHECK,
    SAMPLE_INTAKE_RESET_SLIDE,
    SAMPLE_INTAKE_GRAB_RESET,
    SAMPLE_INTAKE_RELEASE_ELBOWS_DELAY,


    // Outtake sequence
    SAMPLE_INTAKE_TARGET,
    SAMPLE_OUTTAKE_SLIDES_EXTEND,
    SAMPLE_OUTTAKE_ELBOW_BASKET,
    SAMPLE_OUTTAKE_DUMP,
    SAMPLE_OUTTAKE_COMPLETE_WAIT,

    // Sample special
    SAMPLE_REMOVE_FROM_INTAKE,
    SAMPLE_REMOVE_FROM_OUTTAKE,

    // ===== SPECIMEN MODE STATES =====
    // Specimen Outtake sequence
    SPECIMEN_OUTTAKE_ELBOW_INTAKE,
    SPECIMEN_OUTTAKE_CLAW_CLOSE,
    SPECIMEN_OUTTAKE_SLIDE_LIFT,
    SPECIMEN_OUTTAKE_PREPARE,
    SPECIMEN_OUTTAKE_CHECK,
    SPECIMEN_OUTTAKE_SCORE,
    SPECIMEN_OUTTAKE_RELEASE,

    // Specimen intake (external) sequence
    SPECIMEN_INTAKE_POSITION_OUTTAKE,
    SPECIMEN_INTAKE_CLOSE,
    SPECIMEN_INTAKE_TARGET,
    SPECIMEN_INTAKE_CLAW_CLOSE,
    SPECIMEN_INTAKE_READY,
    SPECIMEN_INTAKE_HOLD_OPTION,
    SPECIMEN_INTAKE_CANCEL,
    SPECIMEN_INTAKE_RETRACT_SLIDE,
    SPECIMEN_INTAKE_EXTEND_SLIDE,
    SPECIMEN_INTAKE_RETRIEVE_SAMPLE,
    SPECIMEN_INTAKE_RELEASE_SAMPLE,
    SPECIMEN_INTAKE_CHECK_SAMPLE,
    SPECIMEN_INTAKE_RESET_PICKED,
    SPECIMEN_INTAKE_POSITION_CHECK,
    SPECIMEN_INTAKE_GRAB,
    SPECIMEN_INTAKE_GRAB_CLOSE,
    SPECIMEN_INTAKE_TARGET_CHECK,
    SPECIMEN_INTAKE_GRAB_RESET,

    INTAKE_REMOVE_OPPONENT_SAMPLE,
    INTAKE_RELEASE_OPPONENT_SAMPLE,
    INTAKE_REMOVE_RESET,
    INTAKE_REMOVE_RESET_TURRET

}
